pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "JitPack"
            url = "https://jitpack.io"
        }
    }

    plugins {
        id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    }
}

rootProject.name = 'SoTerm'