package com.github.gameringop.features.impl.visual.hollows

import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.Blocks
import net.minecraft.world.level.block.SlabBlock
import net.minecraft.world.level.block.state.properties.EnumProperty
import net.minecraft.world.level.block.state.properties.SlabType

enum class Structure(
    val blocks: List<Triple<Block?, EnumProperty<*>?, Comparable<*>?>>,
    val structureType: StructureType,
    val quarter: CrystalHollowsQuarter,
    val displayName: String,
    private val configProvider: () -> StructureEspConfig,
    val offsetX: Int,
    val offsetY: Int,
    val offsetZ: Int,
) {
    KING(
        listOf(
            Triple(Blocks.RED_WOOL, null, null),
            Triple(Blocks.DARK_OAK_STAIRS, null, null),
            Triple(Blocks.DARK_OAK_STAIRS, null, null),
            Triple(Blocks.DARK_OAK_STAIRS, null, null),
        ),
        StructureType.CH_CRYSTALS,
        CrystalHollowsQuarter.GOBLIN_HOLDOUT,
        "King",
        { WorldScanner.amberSettings },
        1, -1, 2,
    ),
    QUEEN(
        listOf(
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.ACACIA_WOOD, null, null),
            Triple(Blocks.ACACIA_WOOD, null, null),
            Triple(Blocks.ACACIA_WOOD, null, null),
            Triple(Blocks.ACACIA_WOOD, null, null),
            Triple(Blocks.CAULDRON, null, null),
        ),
        StructureType.CH_CRYSTALS,
        CrystalHollowsQuarter.ANY,
        "Queen",
        { WorldScanner.amberSettings },
        0, 5, 0,
    ),
    DIVAN(
        listOf(
            Triple(Blocks.QUARTZ_PILLAR, null, null),
            Triple(Blocks.QUARTZ_STAIRS, null, null),
            Triple(Blocks.STONE_BRICK_STAIRS, null, null),
            Triple(Blocks.CHISELED_STONE_BRICKS, null, null),
        ),
        StructureType.CH_CRYSTALS,
        CrystalHollowsQuarter.MITHRIL_DEPOSITS,
        "Divan",
        { WorldScanner.jadeSettings },
        0, 5, 0,
    ),
    CITY(
        listOf(
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.COBBLESTONE, null, null),
            Triple(Blocks.COBBLESTONE, null, null),
            Triple(Blocks.COBBLESTONE, null, null),
            Triple(Blocks.COBBLESTONE, null, null),
            Triple(Blocks.COBBLESTONE_STAIRS, null, null),
            Triple(Blocks.POLISHED_ANDESITE, null, null),
            Triple(Blocks.POLISHED_ANDESITE, null, null),
            Triple(Blocks.DARK_OAK_STAIRS, null, null),
        ),
        StructureType.CH_CRYSTALS,
        CrystalHollowsQuarter.PRECURSOR_REMNANTS,
        "City",
        { WorldScanner.sapphireSettings },
        24, 0, -17,
    ),
    TEMPLE(
        listOf(
            Triple(Blocks.BEDROCK, null, null),
            Triple(Blocks.BEDROCK, null, null),
            Triple(Blocks.BEDROCK, null, null),
            Triple(Blocks.BEDROCK, null, null),
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.CLAY, null, null),
            Triple(Blocks.CLAY, null, null),
            Triple(Blocks.CLAY, null, null),
            Triple(Blocks.OAK_LEAVES, null, null),
            Triple(Blocks.OAK_LEAVES, null, null),
            Triple(Blocks.LIME_TERRACOTTA, null, null),
            Triple(Blocks.LIME_TERRACOTTA, null, null),
            Triple(Blocks.GREEN_TERRACOTTA, null, null),
        ),
        StructureType.CH_CRYSTALS,
        CrystalHollowsQuarter.ANY,
        "Temple",
        { WorldScanner.amethystSettings },
        -45, 47, -18,
    ),
    BAL(
        listOf(
            Triple(Blocks.LAVA, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
            Triple(Blocks.BARRIER, null, null),
        ),
        StructureType.CH_CRYSTALS,
        CrystalHollowsQuarter.MAGMA_FIELDS,
        "Bal",
        { WorldScanner.topazSettings },
        0, 1, 0,
    ),
    CORLEONE_DOCK(
        listOf(
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(null, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.FIRE, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
        ),
        StructureType.CORLEONE,
        CrystalHollowsQuarter.MITHRIL_DEPOSITS,
        "Corleone Dock",
        { WorldScanner.corleoneSettings },
        23, 11, 17,
    ),
    CORLEONE_HOLE(
        listOf(
            Triple(Blocks.SMOOTH_STONE_SLAB, SlabBlock.TYPE, SlabType.DOUBLE),
            Triple(Blocks.POLISHED_ANDESITE, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.POLISHED_GRANITE, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.LIGHT_GRAY_TERRACOTTA, null, null),
            Triple(Blocks.JUNGLE_STAIRS, null, null),
            Triple(Blocks.GRANITE, null, null),
            Triple(Blocks.POLISHED_GRANITE, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
            Triple(Blocks.STONE_BRICKS, null, null),
        ),
        StructureType.CORLEONE,
        CrystalHollowsQuarter.MITHRIL_DEPOSITS,
        "Corleone Hole",
        { WorldScanner.corleoneSettings },
        -18, -1, 29,
    ),
    KEY_GUARDIAN_SPIRAL(
        listOf(
            Triple(Blocks.JUNGLE_STAIRS, null, null),
            Triple(Blocks.JUNGLE_PLANKS, null, null),
            Triple(Blocks.GLOWSTONE, null, null),
            Triple(Blocks.BROWN_CARPET, null, null),
            Triple(null, null, null),
            Triple(Blocks.JUNGLE_SLAB, null, null),
            Triple(null, null, null),
            Triple(Blocks.JUNGLE_STAIRS, null, null),
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.STONE, null, null),
        ),
        StructureType.KEY_GUARDIAN,
        CrystalHollowsQuarter.JUNGLE,
        "Key Guardian Spiral",
        { WorldScanner.keyGuardianSettings },
        0, 0, 0,
    ),
    KEY_GUARDIAN_TOWER(
        listOf(
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.POLISHED_GRANITE, null, null),
            Triple(Blocks.JUNGLE_SLAB, SlabBlock.TYPE, SlabType.TOP),
            Triple(null, null, null),
            Triple(Blocks.JUNGLE_SLAB, SlabBlock.TYPE, SlabType.TOP),
            Triple(null, null, null),
            Triple(Blocks.JUNGLE_SLAB, SlabBlock.TYPE, SlabType.TOP),
            Triple(null, null, null),
            Triple(Blocks.JUNGLE_SLAB, SlabBlock.TYPE, SlabType.TOP),
            Triple(Blocks.JUNGLE_SLAB, SlabBlock.TYPE, SlabType.TOP),
            Triple(Blocks.JUNGLE_PLANKS, null, null),
        ),
        StructureType.KEY_GUARDIAN,
        CrystalHollowsQuarter.JUNGLE,
        "Key Guardian Tower",
        { WorldScanner.keyGuardianSettings },
        0, 0, 0,
    ),
    XALX(
        listOf(
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.COAL_BLOCK, null, null),
            Triple(Blocks.FIRE, null, null),
            Triple(Blocks.NETHER_QUARTZ_ORE, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
        ),
        StructureType.XALX,
        CrystalHollowsQuarter.GOBLIN_HOLDOUT,
        "Xalx",
        { WorldScanner.xalxSettings },
        -2, 1, -2,
    ),
    PETE(
        listOf(
            Triple(Blocks.NETHERRACK, null, null),
            Triple(Blocks.FIRE, null, null),
            Triple(Blocks.IRON_BARS, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
            Triple(Blocks.AIR, null, null),
        ),
        StructureType.PETE,
        CrystalHollowsQuarter.GOBLIN_HOLDOUT,
        "Pete (3 bears)",
        { WorldScanner.peteSettings },
        0, 0, 0,
    ),
    ODAWA(
        listOf(
            Triple(Blocks.JUNGLE_LOG, null, null),
            Triple(Blocks.SPRUCE_STAIRS, null, null),
            Triple(Blocks.SPRUCE_STAIRS, null, null),
            Triple(Blocks.JUNGLE_LOG, null, null),
            Triple(Blocks.SPRUCE_STAIRS, null, null),
            Triple(Blocks.SPRUCE_STAIRS, null, null),
            Triple(Blocks.JUNGLE_LOG, null, null),
            Triple(Blocks.JUNGLE_LOG, null, null),
            Triple(Blocks.JUNGLE_LOG, null, null),
            Triple(Blocks.HAY_BLOCK, null, null),
            Triple(Blocks.YELLOW_TERRACOTTA, null, null),
        ),
        StructureType.ODAWA,
        CrystalHollowsQuarter.JUNGLE,
        "Odawa",
        { WorldScanner.odawaSettings },
        0, 0, 0,
    ),
    GOLDEN_DRAGON(
        listOf(
            Triple(Blocks.STONE, null, null),
            Triple(Blocks.RED_TERRACOTTA, null, null),
            Triple(Blocks.RED_TERRACOTTA, null, null),
            Triple(Blocks.RED_TERRACOTTA, null, null),
            Triple(Blocks.PLAYER_HEAD, null, null),
            Triple(Blocks.RED_WOOL, null, null),
        ),
        StructureType.GOLDEN_DRAGON,
        CrystalHollowsQuarter.ANY,
        "Golden Dragon",
        { WorldScanner.goldenDragonSettings },
        0, -3, 5,
    ),
    FAIRY_GROTTO(
        listOf(
            Triple(Blocks.MAGENTA_STAINED_GLASS, null, null),
            Triple(Blocks.MAGENTA_STAINED_GLASS_PANE, null, null),
        ),
        StructureType.FAIRY_GROTTO,
        CrystalHollowsQuarter.ANY,
        "Fairy Grotto",
        { WorldScanner.grottoSettings },
        0, 0, 0,
    ),
    WORM_FISHING(
        listOf(
            Triple(Blocks.LAVA, null, null),
            Triple(Blocks.AIR, null, null),
        ),
        StructureType.WORM_FISHING,
        CrystalHollowsQuarter.PRECURSOR_REMNANTS,
        "Worm Fishing",
        { WorldScanner.wormFishingSettings },
        0, 0, 0,
    );

    val config: StructureEspConfig get() = configProvider()
}
